### ISSUE TITLE
Please add a license file and a readme

### ISSUE THREAD

**Issue by unixorn** [florentinl/omz-wsl#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but I prefer to add plugins with a readme so that users can tell what features they provide and how to use them.

Also, please add a license file, some people won't use any code that doesn't have an open source license. If you don't have one in mind, https://choosealicense.com is a good resource to help you select an appropriate one.

Thanks!

**Comment by florentinl** [comment]
It is done, thanks for your feedback.
